export const books = [
    {
        "id": 1,
        "title": "The God of Small Things",
        "author": "Arundhati Roy",
        "description": "A novel exploring the childhood experiences of fraternal twins in Kerala, India.",
        "category": "Fiction",
        "releasedYear": 1997,
        "imageSrc": "https://i.cbc.ca/1.4223910.1501161009!/fileImage/httpImage/image.png_gen/derivatives/original_780/book-cover-the-god-of-small-things-by-arundhati-roy.png",
        "rating": 4.6,
        "country": "India"
    },
    {
        "id": 2,
        "title": "Midnight's Children",
        "author": "Salman Rushdie",
        "description": "A magical realist novel about India's transition from British colonialism to independence.",
        "category": "Fiction",
        "releasedYear": 1981,
        "imageSrc": "https://entertainment.time.com/wp-content/uploads/sites/3/2011/07/t100_novels_midnightschildren.jpg?w=270",
        "rating": 4.7,
        "country": "India"
    },
    {
        "id": 3,
        "title": "The White Tiger",
        "author": "Aravind Adiga",
        "description": "A dark and gripping novel about the disparities of wealth and power in modern India.",
        "category": "Fiction",
        "releasedYear": 2008,
        "imageSrc": "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781416562733/the-white-tiger-9781416562733_hr.jpg",
        "rating": 4.3,
        "country": "India"
    },
    {
        "id": 4,
        "title": "A Suitable Boy",
        "author": "Vikram Seth",
        "description": "A sweeping novel that follows four families in post-independence India.",
        "category": "Historical Fiction",
        "releasedYear": 1993,
        "imageSrc": "https://i.thenile.io/r1000/9781474618793.jpg?r=5f85e4484ebc5",
        "rating": 4.5,
        "country": "India"
    },
    {
        "id": 5,
        "title": "Train to Pakistan",
        "author": "Khushwant Singh",
        "description": "A powerful novel set during the Partition of India, portraying the human toll of this historical event.",
        "category": "Historical Fiction",
        "releasedYear": 1956,
        "imageSrc": "https://cloudfront.penguin.co.in/wp-content/uploads/2023/02/9780670098163.jpg",
        "rating": 4.4,
        "country": "India"
    },
    {
        "id": 6,
        "title": "The Inheritance of Loss",
        "author": "Kiran Desai",
        "description": "A Man Booker Prize-winning novel set in the northeastern Himalayas, exploring identity and belonging.",
        "category": "Fiction",
        "releasedYear": 2006,
        "imageSrc": "https://odishabytes.com/wp-content/uploads/2020/10/inheritance-of-loss-1336x2048.jpg",
        "rating": 4.1,
        "country": "India"
    },
    {
        "id": 7,
        "title": "The Palace of Illusions",
        "author": "Chitra Banerjee Divakaruni",
        "description": "A retelling of the Mahabharata from the perspective of Draupadi, a key figure in Indian mythology.",
        "category": "Mythology",
        "releasedYear": 2008,
        "imageSrc": "https://th.bing.com/th/id/OIP.BH7wuRtHPHss4izyvAEYGgHaLe?rs=1&pid=ImgDetMain",
        "rating": 4.5,
        "country": "India"
    },
    {
        "id": 8,
        "title": "Shantaram",
        "author": "Gregory David Roberts",
        "description": "A novel about an Australian fugitive who finds a new life in the underworld of Bombay.",
        "category": "Fiction",
        "releasedYear": 2003,
        "imageSrc": "https://th.bing.com/th/id/R.f23a2264ae148575cf8e0b70f98609f0?rik=7%2fuzBF6EEYDg2g&riu=http%3a%2f%2frodolfogrimaldi.com%2fwp-content%2fuploads%2f2015%2f03%2fShantaram-Book-Cover-620x958.jpg&ehk=7z7J561B92MPBdZwx%2b4RRGJSz7OJ1y3runt7mibRlCM%3d&risl=&pid=ImgRaw&r=0",
        "rating": 4.6,
        "country": "Australia"
    },
    {
        "id": 9,
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "description": "A romantic novel critiquing the British landed gentry of the early 19th century.",
        "category": "Romance",
        "releasedYear": 1813,
        "imageSrc": "https://cdn2.penguin.com.au/covers/original/9780141330167.jpg",
        "rating": 4.9,
        "country": "UK"
    },
    {
        "id": 10,
        "title": "1984",
        "author": "George Orwell",
        "description": "A dystopian novel that delves into themes of surveillance and totalitarianism.",
        "category": "Dystopian",
        "releasedYear": 1949,
        "imageSrc": "https://th.bing.com/th/id/OIP.gX0ExEtzFf0AkuD2xmX2iAHaMF?rs=1&pid=ImgDetMain",
        "rating": 4.7,
        "country": "UK"
    },
    {
        "id": 11,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "description": "A novel about racial injustice and the loss of innocence in the Deep South of the United States.",
        "category": "Classic",
        "releasedYear": 1960,
        "imageSrc": "https://cdn2.penguin.com.au/covers/original/9781785150357.jpg",
        "rating": 4.8,
        "country": "US"
    },
    {
        "id": 12,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "description": "A novel set in the Jazz Age, exploring themes of decadence, idealism, and social upheaval.",
        "category": "Classic",
        "releasedYear": 1925,
        "imageSrc": "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9780743273565/the-great-gatsby-9780743273565_hr.jpg",
        "rating": 4.5,
        "country": "US"
    },
    {
        "id": 13,
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "description": "A story of friendship and redemption set against the backdrop of Afghanistan’s history.",
        "category": "Historical Fiction",
        "releasedYear": 2003,
        "imageSrc": "https://m.media-amazon.com/images/I/71TUmY1RDNL._SL1500_.jpg",
        "rating": 4.6,
        "country": "Afghanistan"
    },
    {
        "id": 14,
        "title": "One Hundred Years of Solitude",
        "author": "Gabriel García Márquez",
        "description": "A landmark novel in magical realism, telling the multi-generational story of the Buendía family.",
        "category": "Magical Realism",
        "releasedYear": 1967,
        "imageSrc": "https://th.bing.com/th/id/OIP.TaxDy997JFc65YZBBDAvcAHaLW?rs=1&pid=ImgDetMain",
        "rating": 4.8,
        "country": "Colombia"
    },
    {
        "id": 15,
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "description": "A philosophical tale about following one's dreams and seeking treasure within.",
        "category": "Fiction",
        "releasedYear": 1988,
        "imageSrc": "https://cdn.kobo.com/book-images/32ad8373-9cc5-4c4f-aa82-8155edbc7029/1200/1200/False/the-alchemist-a-graphic-novel.jpg",
        "rating": 4.4,
        "country": "Brazil"
    },
    {
        "id": 16,
        "title": "The Shadow of the Wind",
        "author": "Carlos Ruiz Zafón",
        "description": "A novel about a mysterious book and a young boy’s quest to discover its secrets, set in post-war Barcelona.",
        "category": "Historical Fiction",
        "releasedYear": 2001,
        "imageSrc": "https://i.pinimg.com/originals/99/6b/1a/996b1a484ca909f8f92f71451f8913f7.jpg",
        "rating": 4.7,
        "country": "Spain"
    },
    {
        "id": 17,
        "title": "The Diary of a Young Girl",
        "author": "Anne Frank",
        "description": "The poignant, true account of a Jewish girl hiding during WWII, sharing her thoughts and dreams.",
        "category": "Biography",
        "releasedYear": 1947,
        "imageSrc": "https://m.media-amazon.com/images/I/511ck6vw54L.jpg",
        "rating": 4.8,
        "country": "Netherlands"
    },
    {
        "id": 18,
        "title": "Long Walk to Freedom",
        "author": "Nelson Mandela",
        "description": "An autobiography chronicling Mandela’s fight against apartheid in South Africa.",
        "category": "Biography",
        "releasedYear": 1994,
        "imageSrc": "https://th.bing.com/th/id/OIP.Vxg2VLFSqeaOXb4taHn2XgAAAA?rs=1&pid=ImgDetMain",
        "rating": 4.7,
        "country": "South Africa"
    },
    {
        "id": 19,
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "description": "A biography of Steve Jobs, covering his career, personality, and contributions to technology.",
        "category": "Biography",
        "releasedYear": 2011,
        "imageSrc": "https://th.bing.com/th/id/OIP.zvG9Yx7dDPsmWabttjTzQQHaLh?rs=1&pid=ImgDetMain",
        "rating": 4.6,
        "country": "USA"
    },
    {
        "id": 20,
        "title": "Becoming",
        "author": "Michelle Obama",
        "description": "A personal and inspiring memoir by former First Lady Michelle Obama.",
        "category": "Biography",
        "releasedYear": 2018,
        "imageSrc": "https://cdn2.penguin.com.au/covers/original/9780241334140.jpg",
        "rating": 4.7,
        "country": "USA"
    },
    {
        "id": 21,
        "title": "The Power of Now",
        "author": "Eckhart Tolle",
        "description": "A guide on mindfulness and living in the present moment to find peace and enlightenment.",
        "category": "Self-Help",
        "releasedYear": 1997,
        "imageSrc": "https://is5-ssl.mzstatic.com/image/thumb/Publication4/v4/65/87/83/658783da-e7cd-eb8d-8498-a0d4a3acebda/source/1200x630bb.jpg",
        "rating": 4.6,
        "country": "Germany"
    },
    {
        "id": 22,
        "title": "The 5 AM Club",
        "author": "Robin Sharma",
        "description": "A motivational book encouraging early rising to achieve success and wellness.",
        "category": "Self-Help",
        "releasedYear": 2018,
        "imageSrc": "https://www.libertybooks.com/image/cache/catalog/9780008312831-8-640x996.jpg?q6",
        "rating": 4.4,
        "country": "Canada"
    },
    {
        "id": 23,
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "A practical guide on building good habits and breaking bad ones to improve daily life.",
        "category": "Self-Help",
        "releasedYear": 2018,
        "imageSrc": "https://th.bing.com/th/id/R.4aff834102e39983dbfe729aa722b196?rik=A5vpCLlV%2bkGmdw&riu=http%3a%2f%2fcustomizedcode.us%2fwp-content%2fuploads%2f2020%2f01%2fAtomic-Habits-book-cover.png&ehk=TJ6yulMrix7XXBR2mWS9D2skARdPnOLdFPCt6CNzmig%3d&risl=&pid=ImgRaw&r=0",
        "rating": 4.8,
        "country": "USA"
    },
    {
        "id": 24,
        "title": "The Art of Happiness",
        "author": "Dalai Lama",
        "description": "A discussion on achieving happiness through mental and emotional well-being.",
        "category": "Self-Help",
        "releasedYear": 1998,
        "imageSrc": "https://th.bing.com/th/id/OIP.SR-yW_gEoUqwG1HGAK4mMgHaLG?rs=1&pid=ImgDetMain",
        "rating": 4.7,
        "country": "Tibet"
    },
    {
        "id": 25,
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "description": "A historical examination of the evolution of humans and societies.",
        "category": "Non-Fiction",
        "releasedYear": 2011,
        "imageSrc": "https://www.bookishelf.com/wp-content/uploads/2020/07/Book-Review-Sapiens-A-Brief-History-of-Humankind-1334x2048.jpg",
        "rating": 4.7,
        "country": "Israel"
    },
    {
        "id": 26,
        "title": "The Subtle Art of Not Giving a F*ck",
        "author": "Mark Manson",
        "description": "A refreshing take on how to focus on what really matters in life.",
        "category": "Self-Help",
        "releasedYear": 2016,
        "imageSrc": "https://th.bing.com/th/id/OIP.x7l-LJvOS57awJ0k8uLOKwHaLh?rs=1&pid=ImgDetMain",
        "rating": 4.3,
        "country": "USA"
    },
    {
        "id": 27,
        "title": "Educated",
        "author": "Tara Westover",
        "description": "A memoir about a woman who grows up in a strict family but eventually pursues formal education.",
        "category": "Biography",
        "releasedYear": 2018,
        "imageSrc": "https://th.bing.com/th/id/OIP.Kn8v8LjGkvpgg8BanIjFnAHaLQ?rs=1&pid=ImgDetMain",
        "rating": 4.7,
        "country": "USA"
    },
    {
        "id": 28,
        "title": "Ikigai: The Japanese Secret to a Long and Happy Life",
        "author": "Héctor García and Francesc Miralles",
        "description": "An exploration of the Japanese philosophy of Ikigai, the reason to live and thrive.",
        "category": "Self-Help",
        "releasedYear": 2016,
        "imageSrc": "https://cf.shopee.com.my/file/e16efe88e20646b11e9b8c64d957b55d",
        "rating": 4.5,
        "country": "Japan"
    },
    {
        "id": 29,
        "title": "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "description": "A memoir and exploration of finding purpose and meaning amidst suffering.",
        "category": "Self-Help",
        "releasedYear": 1946,
        "imageSrc": "https://images.thenile.io/r1000/9781846041242.jpg",
        "rating": 4.8,
        "country": "Austria"
    }
];
